### ISSUE TITLE
Windows 8.1 code

### ISSUE THREAD

**Issue by vicenteicc2008** [microsoft/rust_fallible_vec#9]
I need the source code of Windows 8.1 since I want to port the code to ARM64 since I would like to see Windows RT 8.1 in arm64

so could you release me the code please?

**Comment by dpaoliello** [comment]
I'm afraid this is not the correct place to make such a request.
Windows 10 and 11 are both supported on ARM64 - I recommend using one of them instead.

**Comment by vicenteicc2008** [comment]
Or start screen code to port it to arm64

**Comment by dpaoliello** [comment]
I honestly have no idea - you could try asking https://twitter.com/OpenAtMicrosoft if they could recommend a channel.
